env: "local" # local, prod
RestServer:
  host: ""
  port: ""
logger:
  logger_file_path: "../logs.txt" #keep empty for no log file
postgres_db:
  user: ""
  password: ""
  host: "" #ignored if used by docker
  sslmode: ""
  port: ""
rewards: #rewards in points for activities
  10k_daily_steps: 2
  wake_in_time: 1
  8h_sleep: 3
  10_pushups: 1
  inviting_a_friend: 10 #Удаление этой награды сломает процесс добавление рефералов, не меняйте название награды
  being_invited: 5 #Не меняйте название награды
  morning_exercise: 5